export const roles = [
  { value: 'Super-Admin', label: 'Super Admin' },
  { value: 'General-editor', label: 'Головний редактор' },
  { value: 'Editor-main-editorial', label: 'Редактор головної редакції' },
  { value: 'Journalist-main-editorial', label: 'Журналіст головної редакції' },
  { value: 'Partners', label: 'Партнер ММ' },
  { value: 'Editor-Kyiv-MR', label: 'Редактор Київського МР' },
  { value: 'Editor-Southern-MR', label: 'Редактор Південного МР' },
  { value: 'Editor-Dniprovskyi-MR', label: 'Редактор Дніпровського МР' },
  { value: 'Editor-Eastern-MR', label: 'Редактор Східного МР' },
  { value: 'Editor-Western MR', label: 'Редактор Західного МР' },
  { value: 'Correspondent-Kyiv-MR', label: 'Кореспондент Київського МР' },
  { value: 'Correspondent-Southern-MR', label: 'Кореспондент Південного МР' },
  {
    value: 'Correspondent-Dniprovskyi-MR',
    label: 'Кореспондент Дніпровського МР',
  },
  { value: 'Correspondent-Eastern-MR', label: 'Кореспондент Східного МР' },
  { value: 'Correspondent-Western-MR', label: 'Кореспондент Західного МР' },
  { value: 'Manager-Kyiv-MR', label: 'Менеджер Київського МР' },
  { value: 'Manager-Southern-MR', label: 'Менеджер Південного МР' },
  { value: 'Manager-Dniprovskyi-MR', label: 'Менеджер Дніпровського МР' },
  { value: 'Manager-Eastern-MR', label: 'Менеджер Східного МР' },
  { value: 'Manager-Western-MR', label: 'Менеджер Західного МР' },
];
