export const Paths = {
  home: '/',
  login: '/login',
  employees: '/employees',
  employee: '/employee',
  employeeAdd: '/employee/add',
  employeeEdit: '/employee/edit',
  news: '/news',
  newsAdd: '/news/add',
  newsEdit: '/news/edit',
  banners: '/banners',
  banner: '/banner',
  bannerAdd: '/banner/add',
  bannerEdit: '/banner/edit',
  media: '/media',
  status: '/status',
  //Kyiv Region
  berezanNews: '/berezan/news',
  bilacerkvaNews: '/bilacerkva/news',
  boryspilNews: '/boryspil/news',
  boyarkaNews: '/boyarka/news',
  brovaryNews: '/brovary/news',
  buchaNews: '/bucha/news',
  fastivNews: '/fastiv/news',
  irpinNews: '/irpin/news',
  kyivNews: '/kyiv/news',
  obukhivNews: '/obukhiv/news',
  pereyaslavNews: '/pereyaslav/news',
  skvyraNews: '/skvyra/news',
  slavutychNews: '/slavutych/news',
  vasylkivNews: '/vasylkiv/news',
  vyshhorodNews: '/vyshhorod/news',
  vyshneveNews: '/vyshneve/news',
  yagotynNews: '/yagotyn/news',
  // OdesaRegion
  bilgorodDnistrovskyNews: '/bilgorod-dnistrovsky/news',
  chornomorskNews: '/chornomorsk/news',
  izmailNews: '/izmail/news',
  kiliyaNews: '/kiliya/news',
  odesaNews: '/odesa/news',
  podilskNews: '/podilsk/news',
  youzhneNews: '/youzhne/news',
} as const;

// ...cities.cities.reduce(
//   (acc, city) => ({
//     ...acc,
//     [`${city}Posts`]: `/${city}/posts`,
//     [`${city}Post`]: `/${city}/post`,
//   }),
//   {},
// ),
