export const Paths = {
  home: '/',
  login: '/login',
  employees: '/employees',
  employee: '/employee',
  employeeAdd: '/employee/add',
  employeeEdit: '/employee/edit',
  posts: '/posts',
  post: '/post',
  postAdd: '/post/add',
  postEdit: '/post/edit',
  banners: '/banners',
  banner: '/banner',
  bannerAdd: '/banner/add',
  bannerEdit: '/banner/edit',
  media: '/media',
  status: '/status',
} as const;
